apiVersion: v1
kind: Pod
metadata:
  name: tmp-shell
spec:
  hostPID: true
  hostNetwork: true
  containers:
  - name: netshoot
    image: ubuntu
    command: ["sleep", "infinity"] 
    securityContext:
      privileged: true
