apiVersion: v2
name: metrics-server
description: Metrics Server is a scalable, efficient source of container resource metrics for Kubernetes built-in autoscaling pipelines.
type: application
version: 3.12.1
appVersion: 0.7.1
keywords:
  - kubernetes
  - metrics-server
  - metrics
home: https://github.com/kubernetes-sigs/metrics-server
icon: https://avatars.githubusercontent.com/u/36015203?s=400&v=4
sources:
  - https://github.com/kubernetes-sigs/metrics-server
maintainers:
  - name: stevehipwell
    url: https://github.com/stevehipwell
  - name: krmichel
    url: https://github.com/krmichel
  - name: endrec
    url: https://github.com/endrec
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Updated the _Metrics Server_ OCI image to [v0.7.1](https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.7.1)."
